version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r Photo_Album/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping lf1 package..."
      - cd lib
      - zip -r9 ../lf1_package.zip .
      - cd ..
      - zip -g lf1_package.zip Photo_Album/lf1.py
      - echo "Zipping lf2 package..."
      - cd lib
      - zip -r9 ../lf2_package.zip .
      - cd ..
      - zip -g lf2_package.zip Photo_Album/lf2.py