version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - cd Photo_Album
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping LF1 package..."
      - cd lib
      - zip -r9 ../../LF1_package.zip .
      - cd ..
      - zip -g ../LF1_package.zip LF1/lambda_function.py
      - echo "Zipping LF2 package..."
      - cd lib
      - zip -r9 ../../LF2_package.zip .
      - cd ..
      - zip -g ../LF2_package.zip LF2/lambda_function.py
      - cd ..
artifacts:
  files:
    - '**/*'