version: 0.2
phases:
  build:
    commands:
      - cd Photo_Album
      - echo "Zipping frontend code..."
      - cd frontend
      - zip -r9 ../../frontend_package.zip .
      - cd ..
      - cd ..
artifacts:
  files:
    - '**/*'