kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 15s
      slack_api_url: 'https://hooks.slack.com/services/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'
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#assignment'
        send_resolved: true