version: '3'

services:
  # Flask App Service
  flask-app:
    image: myflaskapp:l1  # Use the name and tag you specified during the Docker image build
    ports:
      - "5000:5000"  # Map port 80 inside the container to port 5000 on the host
    depends_on:
      - mongodb  # Wait for the MongoDB service to be ready before starting the Flask app
    environment:
      MONGO_HOST: "mongodb"  # MongoDB service name in the Docker Compose network
      MONGO_PORT: 27017  # MongoDB default port
    volumes:
      - .:/app  # Mount the local app directory to the /app directory inside the container

  # MongoDB Service
  mongodb:
    image: mongo:latest  # Use the latest official MongoDB image from DockerHub
    ports:
      - "27017:27017"  # Map MongoDB default port
    volumes:
      - ./mongodata:/data/db  # Mount a local directory to store MongoDB data
