apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"  # Replace with your app's port
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: homelanderstrikes/todoapp:p7_3  # Replace with your Docker Hub repository information
        ports:
        - containerPort: 5000
        env:
            - name: MONGO_HOST
              value: "mongodb-service"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1